(() => {
var ns = (self.AegisBackground ||= {})

ns.constants = {
  DB_NAME: "aegisstream-cache",
  DB_VERSION: 3,
  STORE_CHUNKS: "chunks",
  STORE_ALIASES: "aliases",
  PREFETCH_CONCURRENCY: 3,
  GLOBAL_MAX_INFLIGHT_PREFETCHES: 12,
  PREFETCH_BATCH_INFLIGHT_CAP: 8,
  PREFETCH_CAP_RETRY_BASE_MS: 200,
  PREFETCH_CAP_RETRY_MAX_MS: 3_200,
  PREFETCH_CAP_RETRY_MAX_ATTEMPTS: 10,
  PREFETCH_QUEUE_MAX_AGE_MS: 15_000,
  PREFETCH_ANCHOR_COOLDOWN_MS: 2_500,
  CHUNK_OBSERVED_DEBOUNCE_MS: 2_000,
  RAPID_SEEK_WINDOW_MS: 2_000,
  RAPID_SEEK_CHANGE_THRESHOLD: 5,
  RAPID_SEEK_PAUSE_MS: 2_500,
  PREFETCH_BATCH_DEBOUNCE_MS: 80,
  PREFETCH_DUPLICATE_WINDOW_MS: 1200,
  PREFETCH_INFLIGHT_TTL_MS: 12_000,
  PREFETCH_BASE_RETRY_MS: 2_500,
  PREFETCH_MAX_RETRY_MS: 120_000,
  PREFETCH_MAX_BACKOFF_EXPONENT: 6,
  PREFETCH_TAB_BURST_WINDOW_MS: 5_000,
  PREFETCH_TAB_BURST_THRESHOLD: 8,
  PREFETCH_BURST_WINDOW_CAP: 8,
  PREFETCH_LOG_THROTTLE_MS: 5_000,
  MAX_MASTER_VARIANTS_TO_SCAN: 6,
  SPECULATIVE_MIN_RUNWAY_SEC: 15,
  SPECULATIVE_MATRIX_MAX_RUNGS: 6,
  SPECULATIVE_SEGMENTS_AHEAD: 2,
  SPECULATIVE_MAX_URLS_PER_CYCLE: 10,
  SPECULATIVE_CYCLE_MIN_MS: 2_000,
  SPECULATIVE_MIN_SAMPLES_FOR_ADAPTIVE: 20,
  SPECULATIVE_HIT_RATE_DISABLE_PCT: 5,
  SPECULATIVE_HIT_RATE_FULL_PCT: 40,
  PREFETCH_FAILURE_COOLDOWN_MS: 15_000,
  MANIFEST_REFRESH_DEBOUNCE_MS: 4_000,
  MANIFEST_REFRESH_TIMEOUT_MS: 20_000,
  MANIFEST_REFRESH_MAX_RETRIES: 5,
  MANIFEST_REFRESH_RETRY_BASE_MS: 1_000,
  MANIFEST_REFRESH_RETRY_MAX_MS: 8_000,
  AUTH_EXPIRED_RETRY_COOLDOWN_MS: 30_000,
  PREFETCH_AUTH_FAILURE_WINDOW_MS: 4_000,
  PREFETCH_AUTH_FAILURE_THRESHOLD: 3,
  PREFETCH_CONSECUTIVE_MAYBE_AUTH_THRESHOLD: 6,
  PREFETCH_CONSECUTIVE_MAYBE_WITH_AUTH: 4,
  PREFETCH_PAUSE_AFTER_REFRESH_MS: 8_000,
  /** After an episode fingerprint change, do not trigger manifest refresh from prefetch failures. */
  EPISODE_TRANSITION_AUTH_GRACE_MS: 15_000,
  /** Shorter prefetch retry base while episode transition grace is active. */
  EPISODE_PREFETCH_RETRY_BASE_MS: 600,
  /** Shorter refresh timeout while episode transition grace is active. */
  EPISODE_MANIFEST_REFRESH_TIMEOUT_MS: 8_000,
  PREFETCH_EMERGENCY_MIN_GAP_MS: 450,
  PREFETCH_INFLIGHT_RETRY_MS: 450,
  PREFETCH_RATE_LIMIT_PAUSE_MS: 45_000,
  PLAYLIST_ROTATION_GRACE_MS: 10_000,
  REFRESH_RECOVERY_MAX_CHUNKS: 4,
  REFRESH_RECOVERY_SUCCESS_TARGET: 3,
  REFRESH_RECOVERY_MAX_MS: 12_000,
  PREFETCH_NETWORK_MAYBE_AUTH_THRESHOLD: 6,
  PREFETCH_NETWORK_MAYBE_AUTH_WITH_AUTH: 4,
  PLAYLIST_RELAY_TTL_MS: 45_000,
  STALE_TAB_STATE_MS: 10 * 60 * 1000,
  FAILURE_STATE_RETENTION_MS: 5 * 60 * 1000,
  CACHE_POLICY_REFRESH_MS: 30_000,
  CACHE_RECONCILE_INTERVAL_MS: 20_000,
  CACHE_EVICTION_DEBOUNCE_MS: 2_000,
  /** Lane 2 soft threshold — avoid IDB scans when cache is comfortably below budget. */
  CACHE_EVICTION_SOFT_BYTES_RATIO: 0.85,
  CACHE_EVICTION_SOFT_ENTRIES_RATIO: 0.9,
  /** Lane 1 hard breaker — bypasses scrub suppression before quota failure. */
  CACHE_EVICTION_HARD_BYTES_RATIO: 0.95,
  CACHE_EVICTION_HARD_ENTRIES_RATIO: 0.95,
  /** Lane 3 lazy reconcile runs only above this fill ratio (steady playback). */
  CACHE_EVICTION_LANE3_MIN_RATIO: 0.7,
  CACHE_EVICTION_SCRUB_DEFER_MS: 5_000,
  CACHE_EVICTION_LANE3_INTERVAL_MS: 45_000,
  CACHE_DUPLICATE_WRITE_WINDOW_MS: 20_000,
  CACHE_MAX_EVICTION_BATCH: 120,
  CACHE_POLICY_HEADROOM_BYTES: 96 * 1024 * 1024,
  CACHE_MIN_BYTES: 96 * 1024 * 1024,
  CACHE_MAX_BYTES: 1024 * 1024 * 1024,
  CACHE_QUOTA_TARGET_FRACTION: 0.12,
  CACHE_FREE_SPACE_TARGET_FRACTION: 0.35,
  CACHE_DEFAULT_AVG_CHUNK_BYTES: 384 * 1024,
  TAB_BRIDGE_RECHECK_MS: 15_000,
  TAB_BRIDGE_PING_RETRIES: 3,
  TAB_BRIDGE_PING_RETRY_MS: 200,
  BACKGROUND_INIT_DEBOUNCE_MS: 5_000,
  MAX_LOG_ENTRIES: 500,
  MAX_CACHE_KEY_VARIANTS: 6,
  MAX_TTFB_SAMPLES: 240,
  UMP_HEALTH_LOG_INTERVAL_MS: 15_000,
  UMP_WARMUP_LOOKUP_LIMIT: 6,
  BUFFER_RUNWAY_EMERGENCY_SEC: 5,
  BUFFER_RUNWAY_AGGRESSIVE_SEC: 15,
  BUFFER_RUNWAY_NORMAL_SEC: 30,
  BUFFER_RUNWAY_MAINTENANCE_SEC: 60,
  BUFFER_TARGET_RUNWAY_SEC: 60,
  PANIC_TARGET_RUNWAY_SEC: 180,
  PANIC_PREFETCH_WINDOW: 20,
  TTFB_PANIC_ENTER_P95_MS: 3000,
  TTFB_PANIC_EXIT_P95_MS: 2400,
  TTFB_PANIC_MIN_NETWORK_SAMPLES: 12,
  BUFFER_HEALTH_SAMPLE_MS: 750,
  BUFFER_HEALTH_STALE_MS: 8_000,
  BUFFER_HEALTH_SECURE_RUNWAY_SEC: 15,
  BUFFER_HEALTH_EMA_ALPHA: 0.2,
  BUFFER_HEALTH_MIN_SCORE_WHEN_SECURE: 20,
  ANCHOR_CONFIRM_MS: 1_500,
  ANCHOR_CONFIRM_SAMPLES: 3,
  ANCHOR_MONOTONIC_STREAK_THRESHOLD: 2,
  ANCHOR_TELEPORT_JUMP_THRESHOLD: 5,
  DOM_TELEPORT_MIN_JUMP: 2,
  /** Trailing path fingerprint length for obfuscated CDN segment blobs (page vs prefetch URL alignment). */
  MEDIA_CACHE_INVARIANT_TAIL_LEN: 56,
  CACHE_REGISTRY_MAX_KEYS: 800,
  CACHE_REGISTRY_SYNC_DEBOUNCE_MS: 150,
  /** Debounce rapid teleport anchor shifts before tearing down prefetch windows. */
  TELEPORT_DEBOUNCE_MS: 150,
  /** Background cache lookup waits for in-flight prefetch to land in IDB. */
  CACHE_LOOKUP_COLLAPSE_WAIT_MS: 8_000,
  DOM_TELEPORT_COOLDOWN_MS: 500,
  DOM_ANCHOR_COALESCE_MS: 40,
  SCRUB_DOM_ANCHOR_COALESCE_MS: 120,
  SCRUB_DOM_PURGE_JUMP_THRESHOLD: 2,
  /** Keeps MV3 service worker warm during active playback (Chrome idle ~30s). */
  WORKER_LIVELINESS_PING_MS: 10_000,
  /** Rapid timeline scrubbing: seeks closer than this apart activate the scrubbing train. */
  SCRUBBING_TRAIN_SEEK_INTERVAL_MS: 800,
  /** Keep scrubbing train active until no rapid seek for this long. */
  SCRUBBING_TRAIN_IDLE_MS: 1_000,
  /** After a DOM hard commit during scrubbing, ignore passive lane anchor drift. */
  PASSIVE_HYSTERESIS_MUTE_MS: 1_500,
  /** Prefetch ring radius while scrubbing train is active. */
  SCRUBBING_TRAIN_PREFETCH_RADIUS: 2,
  /** Wide forward buffer immediately when the user releases the slider (seeked). */
  SCRUB_SNAP_BACK_RADIUS: 15,
  SCRUB_SNAP_BACK_MS: 5_000,
  SCRUB_SNAP_BACK_TRIGGER_MIN_MS: 900,
  SCRUB_SNAP_BACK_INDEX_DELTA: 3,
  /** Let the page playlist delegate run before the extension background fetch. */
  MANIFEST_REFRESH_PAGE_FIRST_MS: 300,
  VARIANT_SWITCH_COOLDOWN_MS: 2_000,
  /** After manual quality change: ignore spurious DOM teleports near t≈0 while playhead mapping catches up. */
  VARIANT_SWITCH_GRACE_MS: 8_000,
  /** Keep DOM/seek anchors across playlist refresh for this window (prevents end-seek resets). */
  SEEK_ANCHOR_RETAIN_MS: 30_000,
  /** After SW restart, how long to defer quality-rung auto-detection to avoid locking onto low-quality startup chunks. */
  WARM_RECOVERY_RUNG_CONFIRM_MS: 10_000,
  /** Number of consecutive same-quality chunks needed before committing activeRungLabel post-restart. */
  WARM_RECOVERY_RUNG_CONFIRM_SAMPLES: 3,
  /** After SW restart, defer prefetch decisions for this window while rebuilding state. */
  WARM_RECOVERY_DEFER_PREFETCH_MS: 3_000,
  /** After SW restart, run cache-rebuild and state-recovery only; no tab injection. */
  WARM_RECOVERY_STATE_REBUILD_MS: 5_000,
  /** Persist critical tab state snapshot to chrome.storage.session at this interval. */
  STATE_PERSIST_DEBOUNCE_MS: 2_000,
  /** Maximum number of tab state snapshots to keep in storage. */
  STATE_PERSIST_MAX_TABS: 8,
  VARIANT_SWITCH_TELEPORT_SUPPRESS_SEC: 20,
  VARIANT_SWITCH_PREFETCH_WINDOW: 12,
  /** Prefer aggressive forward prefetch over rescue aborts right after a rendition change. */
  VARIANT_SWITCH_RESCUE_DEFER_MS: 4_000,
  TELEPORT_QUEUE_PURGE_THRESHOLD: 20,
  TELEPORT_MODE_JUMP_THRESHOLD: 20,
  TELEPORT_MODE_RADIUS: 5,
  TELEPORT_MODE_DURATION_MS: 8_000,
  SEEK_CHURN_AGGRESSIVE_MS: 4_000,
  SEEK_CHURN_PREFETCH_WINDOW_MIN: 10,
  CACHE_GUARD_RING_PAST_SEGMENTS: 2,
  CACHE_GUARD_RING_FUTURE_SEGMENTS: 12,
  CACHE_GUARD_RING_SEEK_CHURN_PAST: 5,
  CACHE_GUARD_RING_SEEK_CHURN_FUTURE: 24,
  /** Collapse wait: max(1500ms, 2x rolling network TTFB p95), capped below. */
  COLLAPSE_WAIT_MIN_MS: 1_500,
  COLLAPSE_WAIT_MAX_MS: 8_000,
  COLLAPSE_WAIT_P95_MULTIPLIER: 2,
  /** Timeline heat-map eviction: S = D*w_d + H*w_h; protect when S >= threshold. */
  TIMELINE_HEAT_HOT_THRESHOLD: 8,
  TIMELINE_HEAT_PROTECT_MIN_HITS: 4,
  TIMELINE_HEAT_WEIGHT_DISTANCE: 1,
  TIMELINE_HEAT_WEIGHT_HISTORICAL: 4,
  TIMELINE_HEAT_HIT_CAP: 12,
  TIMELINE_HEAT_MAX_MAP_ENTRIES: 400,
  TELEPORT_PRIORITY_LANE_MS: 3_000,
  TELEPORT_LANE_TELEPORT_SHARE: 0.7,
  TELEPORT_LANE_SNAPBACK_SHARE: 0.2,
  SEEK_PREDICTION_MIN_SAMPLES: 8,
  SEEK_PREDICTION_DISABLE_THRESHOLD: 0.35,
  SEEK_PREDICTION_SPECULATIVE_THRESHOLD: 0.75,
  SEEK_PREDICTION_OUTLIER_LAMBDA: 0.02,
  SEEK_UNIFIED_DEBOUNCE_MIN_MS: 30,
  SEEK_UNIFIED_DEBOUNCE_MAX_MS: 150,
  SEEK_PREDICTION_GAUSSIAN_SIGMA: 2,
  SEEK_PREDICTION_CONFIDENCE_EMA_ALPHA: 0.15,
  UNIFIED_SEEK_PASSENGER_MS: 800,
  /** Break passenger lock after seek release when runway is at or below this (seconds). */
  SEEK_PASSENGER_STALL_RUNWAY_SEC: 2,
  /** Window after seeked release where stall/runway can force macro predictor. */
  SEEK_RELEASE_STALL_OVERRIDE_MS: 3_000,
  SCRUB_VELOCITY_MAX_JUMP_SEGMENTS: 8,
  SCRUB_KALMAN_LOOKAHEAD_MIN_MS: 200,
  SCRUB_KALMAN_LOOKAHEAD_MAX_MS: 800,
  SCRUB_KALMAN_LOOKAHEAD_BASE_MS: 200,
  SCRUB_KALMAN_LOOKAHEAD_VELOCITY_MS: 80,
  SPECULATIVE_TARGET_RUNWAY_SEC: 30,
  SPECULATIVE_CONTINUOUS_THRESHOLD: 0.20,
  SPECULATIVE_CONTINUOUS_AGGRESSIVE_THRESHOLD: 0.7,
  SPECULATIVE_CONTINUOUS_RUNWAY_FLOOR_SEC: 5,
  SPECULATIVE_CONGESTED_MULTIPLIER: 0.3,
  SPECULATIVE_NOMINAL_BLOCKED_MULTIPLIER: 0.5,
  RESCUE_RUNWAY_SEC: 3,
  RESCUE_HEALTH_PCT: 5,
  RESCUE_ENTER_RUNWAY_SEC: 3,
  RESCUE_EXIT_RUNWAY_SEC: 5,
  RESCUE_ENTER_HEALTH_PCT: 5,
  RESCUE_EXIT_HEALTH_PCT: 15,
  RESCUE_GENERATION_BUMP_MIN_MS: 800,
  RESCUE_SEGMENTS_AHEAD: 2,
  TEMPERATURE_WEIGHT_FREQUENCY: 4,
  TEMPERATURE_WEIGHT_PROXIMITY: 1.5,
  SCRUB_DELEGATE_MIN_INTERVAL_MS: 400,
  CHURN_PLAYBACK_BUMP_MIN_MS: 900,
  DELEGATE_BATCH_COALESCE_MS: 60,
  SCHEDULER_ARBITRATE_MIN_MS: 200,
  RESCUE_SCHEDULE_MIN_MS: 400,
  SCRUB_VELOCITY_LOOKAHEAD_MS: 400,
  SCRUB_VELOCITY_PREFETCH_RADIUS: 3,
  SCRUB_VELOCITY_MIN_SEGMENTS_PER_SEC: 0.5,
  // Legacy aliases (deprecated names)
  BUFFER_RUNWAY_CRITICAL_SEC: 5,
  BUFFER_RUNWAY_LOW_SEC: 15,
  BUFFER_RUNWAY_COMFORT_SEC: 30,
  BUFFER_RUNWAY_IDLE_SEC: 60,
  VOLATILE_QUERY_PARAMS: new Set([
    "rn",
    "rbuf",
    "alr",
    "cpn",
    "cver",
    "ump",
    "token",
    "sig",
    "signature",
    "expires",
    "expire",
    "hdnts",
    "hdntl",
    "policy",
    "keypairid",
    "session",
    "sessionid",
    "auth",
    "x-amz-signature",
    "x-amz-date",
    "x-amz-expires",
    "x-amz-security-token",
    "x-goog-signature",
    "x-goog-date",
    "x-goog-expires",
    "x-goog-credential"
  ]),
  IDENTITY_QUERY_PARAMS: new Set([
    "range",
    "rbuf",
    "sq",
    "seg",
    "segment",
    "part",
    "bytestart",
    "byteend",
    "start",
    "end",
    "index",
    "itag"
  ]),
  DEFAULT_SETTINGS: {
    enabled: true,
    prefetchEnabled: true,
    serveFromCache: true,
    maxEntries: 500,
    prefetchWindow: 6,
    documentStreamBoost: true,
    headerEarlyHints: true,
    cpuShieldEnabled: true,
    aggressiveScriptDefuserEnabled: false,
    bfcacheEnforcerEnabled: true,
    speculativePrefetchEnabled: true
  },
  createInitialStats() {
    return {
      cacheLookups: 0,
      cacheHits: 0,
      cacheMisses: 0,
      cacheWarmups: 0,
      cachedChunks: 0,
      youtubeUmpChunks: 0,
      youtubeUmpRequests: 0,
      youtubeUmpLookups: 0,
      youtubeUmpLookupHits: 0,
      youtubeUmpLookupMisses: 0,
      youtubeUmpWarmups: 0,
      youtubeUmpUniqueKeys: 0,
      youtubeUmpStreamsCompleted: 0,
      youtubeUmpStreamsAborted: 0,
      youtubeUmpStreamsErrored: 0,
      youtubeUmpCaptureSkipped: 0,
      prefetched: 0,
      prefetchFailed: 0,
      playlistsDetected: 0,
      chunksObserved: 0,
      requestFirstByteSamples: 0,
      requestFirstByteAvgMs: 0,
      requestFirstByteP95Ms: 0,
      networkFirstByteP95Ms: 0,
      networkPanicActive: 0,
      cacheFirstByteAvgMs: 0,
      networkFirstByteAvgMs: 0,
      videoStalls: 0,
      videoStallMsTotal: 0,
      videoStallLongestMs: 0,
      extensionFetchStarted: 0,
      extensionFetchCompleted: 0,
      extensionFetchAborted: 0,
      extensionFetchFailed: 0,
      playlistFingerprintNewPlayback: 0,
      speculativeMatrixBuilt: 0,
      speculativePrefetchScheduled: 0,
      speculativePrefetchStarted: 0,
      speculativePrefetchCompleted: 0,
      speculativePrefetchUsed: 0,
      speculativePrefetchWasted: 0,
      speculativePrefetchExpired: 0,
      speculativeBytesDownloaded: 0,
      speculativeBytesConsumed: 0,
      speculativeBytesWasted: 0,
      speculativeQualitySwitchHits: 0,
      speculativeCrossItagUsed: 0,
      youtubeCrossItagPrefetch: 0,
      anchorCommitsNetwork: 0,
      anchorCommitsSeekPrediction: 0,
      anchorCommitsDomSeeked: 0,
      teleportsHard: 0,
      teleportsSoft: 0,
      monotonicBreakthroughs: 0,
      tokenRefreshRetentions: 0,
      anchorDeferred: 0,
      domSeekSkipped: 0,
      variantSwitchCascadeBlocked: 0,
      domAnchorSupremacyPreserved: 0,
      evictionSuppressedByScrub: 0,
      consumerProtectedSkips: 0
    }
  }
}
})()
