(() => {
var ns = (self.AegisBackground ||= {})

ns.constants = {
  DB_NAME: "aegisstream-cache",
  DB_VERSION: 3,
  STORE_CHUNKS: "chunks",
  STORE_ALIASES: "aliases",
  PREFETCH_CONCURRENCY: 3,
  GLOBAL_MAX_INFLIGHT_PREFETCHES: 12,
  PREFETCH_BATCH_INFLIGHT_CAP: 8,
  PREFETCH_CAP_RETRY_BASE_MS: 200,
  PREFETCH_CAP_RETRY_MAX_MS: 3_200,
  PREFETCH_CAP_RETRY_MAX_ATTEMPTS: 10,
  PREFETCH_QUEUE_MAX_AGE_MS: 15_000,
  PREFETCH_ANCHOR_COOLDOWN_MS: 2_500,
  CHUNK_OBSERVED_DEBOUNCE_MS: 2_000,
  RAPID_SEEK_WINDOW_MS: 2_000,
  RAPID_SEEK_CHANGE_THRESHOLD: 5,
  RAPID_SEEK_PAUSE_MS: 2_500,
  PREFETCH_BATCH_DEBOUNCE_MS: 80,
  PREFETCH_DUPLICATE_WINDOW_MS: 1200,
  PREFETCH_INFLIGHT_TTL_MS: 12_000,
  PREFETCH_BASE_RETRY_MS: 2_500,
  PREFETCH_MAX_RETRY_MS: 120_000,
  PREFETCH_MAX_BACKOFF_EXPONENT: 6,
  PREFETCH_TAB_BURST_WINDOW_MS: 5_000,
  PREFETCH_TAB_BURST_THRESHOLD: 8,
  PREFETCH_BURST_WINDOW_CAP: 8,
  PREFETCH_LOG_THROTTLE_MS: 5_000,
  MAX_MASTER_VARIANTS_TO_SCAN: 3,
  PREFETCH_FAILURE_COOLDOWN_MS: 15_000,
  MANIFEST_REFRESH_DEBOUNCE_MS: 4_000,
  MANIFEST_REFRESH_TIMEOUT_MS: 20_000,
  MANIFEST_REFRESH_MAX_RETRIES: 5,
  MANIFEST_REFRESH_RETRY_BASE_MS: 1_000,
  MANIFEST_REFRESH_RETRY_MAX_MS: 8_000,
  AUTH_EXPIRED_RETRY_COOLDOWN_MS: 30_000,
  PREFETCH_AUTH_FAILURE_WINDOW_MS: 4_000,
  PREFETCH_AUTH_FAILURE_THRESHOLD: 3,
  PREFETCH_CONSECUTIVE_MAYBE_AUTH_THRESHOLD: 6,
  PREFETCH_CONSECUTIVE_MAYBE_WITH_AUTH: 4,
  PREFETCH_PAUSE_AFTER_REFRESH_MS: 8_000,
  PREFETCH_EMERGENCY_MIN_GAP_MS: 450,
  PREFETCH_INFLIGHT_RETRY_MS: 450,
  PREFETCH_RATE_LIMIT_PAUSE_MS: 45_000,
  PLAYLIST_ROTATION_GRACE_MS: 10_000,
  REFRESH_RECOVERY_MAX_CHUNKS: 4,
  REFRESH_RECOVERY_SUCCESS_TARGET: 3,
  REFRESH_RECOVERY_MAX_MS: 12_000,
  PREFETCH_NETWORK_MAYBE_AUTH_THRESHOLD: 6,
  PREFETCH_NETWORK_MAYBE_AUTH_WITH_AUTH: 4,
  PLAYLIST_RELAY_TTL_MS: 45_000,
  STALE_TAB_STATE_MS: 10 * 60 * 1000,
  FAILURE_STATE_RETENTION_MS: 5 * 60 * 1000,
  CACHE_POLICY_REFRESH_MS: 30_000,
  CACHE_RECONCILE_INTERVAL_MS: 20_000,
  CACHE_EVICTION_DEBOUNCE_MS: 2_000,
  CACHE_DUPLICATE_WRITE_WINDOW_MS: 20_000,
  CACHE_MAX_EVICTION_BATCH: 120,
  CACHE_POLICY_HEADROOM_BYTES: 96 * 1024 * 1024,
  CACHE_MIN_BYTES: 96 * 1024 * 1024,
  CACHE_MAX_BYTES: 1024 * 1024 * 1024,
  CACHE_QUOTA_TARGET_FRACTION: 0.12,
  CACHE_FREE_SPACE_TARGET_FRACTION: 0.35,
  CACHE_DEFAULT_AVG_CHUNK_BYTES: 384 * 1024,
  TAB_BRIDGE_RECHECK_MS: 15_000,
  TAB_BRIDGE_PING_RETRIES: 3,
  TAB_BRIDGE_PING_RETRY_MS: 200,
  BACKGROUND_INIT_DEBOUNCE_MS: 5_000,
  MAX_LOG_ENTRIES: 500,
  MAX_CACHE_KEY_VARIANTS: 5,
  MAX_TTFB_SAMPLES: 240,
  UMP_HEALTH_LOG_INTERVAL_MS: 15_000,
  UMP_WARMUP_LOOKUP_LIMIT: 6,
  BUFFER_RUNWAY_EMERGENCY_SEC: 5,
  BUFFER_RUNWAY_AGGRESSIVE_SEC: 15,
  BUFFER_RUNWAY_NORMAL_SEC: 30,
  BUFFER_RUNWAY_MAINTENANCE_SEC: 60,
  BUFFER_TARGET_RUNWAY_SEC: 60,
  PANIC_TARGET_RUNWAY_SEC: 180,
  PANIC_PREFETCH_WINDOW: 20,
  TTFB_PANIC_ENTER_P95_MS: 3000,
  TTFB_PANIC_EXIT_P95_MS: 2400,
  TTFB_PANIC_MIN_NETWORK_SAMPLES: 12,
  BUFFER_HEALTH_SAMPLE_MS: 750,
  BUFFER_HEALTH_STALE_MS: 8_000,
  // Legacy aliases (deprecated names)
  BUFFER_RUNWAY_CRITICAL_SEC: 5,
  BUFFER_RUNWAY_LOW_SEC: 15,
  BUFFER_RUNWAY_COMFORT_SEC: 30,
  BUFFER_RUNWAY_IDLE_SEC: 60,
  VOLATILE_QUERY_PARAMS: new Set([
    "rn",
    "rbuf",
    "alr",
    "cpn",
    "cver",
    "ump",
    "token",
    "sig",
    "signature",
    "expires",
    "expire",
    "hdnts",
    "hdntl",
    "policy",
    "keypairid",
    "session",
    "sessionid",
    "auth",
    "x-amz-signature",
    "x-amz-date",
    "x-amz-expires",
    "x-amz-security-token",
    "x-goog-signature",
    "x-goog-date",
    "x-goog-expires",
    "x-goog-credential"
  ]),
  IDENTITY_QUERY_PARAMS: new Set([
    "range",
    "rbuf",
    "sq",
    "seg",
    "segment",
    "part",
    "bytestart",
    "byteend",
    "start",
    "end",
    "index",
    "itag"
  ]),
  DEFAULT_SETTINGS: {
    enabled: true,
    prefetchEnabled: true,
    serveFromCache: true,
    maxEntries: 500,
    prefetchWindow: 6,
    documentStreamBoost: true,
    headerEarlyHints: true,
    cpuShieldEnabled: true,
    aggressiveScriptDefuserEnabled: false,
    bfcacheEnforcerEnabled: true
  },
  createInitialStats() {
    return {
      cacheLookups: 0,
      cacheHits: 0,
      cacheMisses: 0,
      cacheWarmups: 0,
      cachedChunks: 0,
      youtubeUmpChunks: 0,
      youtubeUmpRequests: 0,
      youtubeUmpLookups: 0,
      youtubeUmpLookupHits: 0,
      youtubeUmpLookupMisses: 0,
      youtubeUmpWarmups: 0,
      youtubeUmpUniqueKeys: 0,
      youtubeUmpStreamsCompleted: 0,
      youtubeUmpStreamsAborted: 0,
      youtubeUmpStreamsErrored: 0,
      youtubeUmpCaptureSkipped: 0,
      prefetched: 0,
      prefetchFailed: 0,
      playlistsDetected: 0,
      chunksObserved: 0,
      requestFirstByteSamples: 0,
      requestFirstByteAvgMs: 0,
      requestFirstByteP95Ms: 0,
      networkFirstByteP95Ms: 0,
      networkPanicActive: 0,
      cacheFirstByteAvgMs: 0,
      networkFirstByteAvgMs: 0,
      videoStalls: 0,
      videoStallMsTotal: 0,
      videoStallLongestMs: 0,
      extensionFetchStarted: 0,
      extensionFetchCompleted: 0,
      extensionFetchAborted: 0,
      extensionFetchFailed: 0,
      playlistFingerprintNewPlayback: 0
    }
  }
}
})()
