import { defineTheme } from "../token-schema.js"

/** Light editorial workspace — crisp borders, indigo accent, compact density */
export const paperTheme = defineTheme({
  id: "paper",
  label: "Paper",
  description: "Bright editorial workspace with crisp borders and indigo accents",
  mode: "light",
  fonts: {
    sans: {
      family: "Source Sans 3",
      weights: "400;500;600;700",
      url: "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;500;600;700&display=swap"
    },
    mono: {
      family: "Source Code Pro",
      weights: "400;500;600",
      url: "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600&display=swap"
    }
  },
  tokens: {
    "background.primary": "#f8fafc",
    "background.secondary": "#f1f5f9",
    "background.gradient-a": "rgba(79, 70, 229, 0.06)",
    "background.gradient-b": "rgba(14, 165, 233, 0.05)",
    "surface.default": "#ffffff",
    "surface.raised": "#f8fafc",
    "surface.sunken": "#eef2f7",
    "surface.overlay": "rgba(15, 23, 42, 0.04)",
    "text.primary": "#0f172a",
    "text.secondary": "#475569",
    "text.tertiary": "#94a3b8",
    "text.inverse": "#ffffff",
    "text.link": "#4f46e5",
    "border.default": "#e2e8f0",
    "border.subtle": "#f1f5f9",
    "border.strong": "#cbd5e1",
    "border.focus": "rgba(79, 70, 229, 0.45)",
    "accent.primary": "#4f46e5",
    "accent.primary-hover": "#6366f1",
    "accent.secondary": "#0ea5e9",
    "accent.glow": "rgba(79, 70, 229, 0.25)",
    "accent.gradient-start": "#4f46e5",
    "accent.gradient-end": "#0ea5e9",
    "status.success": "#059669",
    "status.success-foreground": "#ffffff",
    "status.success-muted-bg": "#ecfdf5",
    "status.success-muted-border": "#a7f3d0",
    "status.warning": "#d97706",
    "status.warning-foreground": "#92400e",
    "status.warning-muted-bg": "#fffbeb",
    "status.warning-muted-border": "#fcd34d",
    "status.danger": "#dc2626",
    "status.danger-foreground": "#ffffff",
    "status.danger-muted-bg": "#fef2f2",
    "status.danger-muted-border": "#fecaca",
    "status.info": "#2563eb",
    "status.info-muted-bg": "#eff6ff",
    "status.info-muted-border": "#bfdbfe",
    "icon.logo-gradient-start": "#4f46e5",
    "icon.logo-gradient-end": "#0ea5e9",
    "shadow.card": "0 1px 3px rgba(15, 23, 42, 0.08), 0 8px 24px rgba(15, 23, 42, 0.06)",
    "shadow.button": "0 4px 14px rgba(79, 70, 229, 0.22)",
    "shadow.glow-accent": "0 0 0 transparent",
    "radius.lg": "12px",
    "radius.md": "8px",
    "radius.sm": "6px",
    "radius.pill": "999px",
    "space.xs": "4px",
    "space.sm": "6px",
    "space.md": "10px",
    "space.lg": "14px",
    "space.xl": "20px",
    "font.family.sans": "'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "font.family.mono": "'Source Code Pro', Consolas, monospace",
    "font.size-xs": "9px",
    "font.size-sm": "11px",
    "font.size-md": "13px",
    "font.size-lg": "14px",
    "font.size-xl": "16px",
    "font.weight-regular": "400",
    "font.weight-medium": "500",
    "font.weight-semibold": "600",
    "font.weight-bold": "700",
    "motion.duration-fast": "0.12s",
    "motion.duration-normal": "0.22s",
    "motion.easing-default": "cubic-bezier(0.4, 0, 0.2, 1)",
    "chart.progress-track": "#e2e8f0",
    "chart.progress-track-border": "#cbd5e1",
    "chart.progress-fill-start": "#4f46e5",
    "chart.progress-fill-end": "#059669",
    "chart.progress-glow": "transparent",
    "input.background": "#ffffff",
    "input.border": "#cbd5e1",
    "input.focus-background": "#eef2ff",
    "input.focus-ring": "rgba(79, 70, 229, 0.2)",
    "switch.track": "#cbd5e1",
    "switch.thumb": "#ffffff",
    "switch.track-active": "#4f46e5",
    "scrollbar.thumb": "#cbd5e1",
    "nav.tab-inactive": "#64748b",
    "nav.tab-active": "#0f172a",
    "nav.tab-indicator-glow": "transparent",
    "button.primary-bg": "#4f46e5",
    "button.primary-fg": "#ffffff",
    "button.primary-hover": "#6366f1",
    "button.secondary-bg": "#ffffff",
    "button.secondary-fg": "#475569",
    "button.secondary-border": "#e2e8f0",
    "button.secondary-hover-bg": "#f8fafc",
    "button.secondary-hover-fg": "#0f172a",
    "button.secondary-hover-border": "#cbd5e1",
    "button.disabled-opacity": "0.55",
    "metric.surface": "#f8fafc",
    "metric.surface-hover": "#f1f5f9",
    "metric.label": "#64748b",
    "metric.value": "#0f172a",
    "badge.experimental-text": "#92400e",
    "badge.experimental-bg-start": "#fffbeb",
    "badge.experimental-bg-end": "#fef3c7",
    "badge.experimental-border": "#fcd34d",
    "badge.experimental-dot": "#d97706",
    "badge.experimental-row-bg-start": "#fffbeb",
    "badge.experimental-row-border": "#fcd34d",
    "scope.badge-text": "#4338ca",
    "scope.badge-bg": "#eef2ff",
    "scope.badge-border": "#c7d2fe",
    "speculative.accent-border": "#c7d2fe",
    "speculative.mode-text": "#047857",
    "speculative.mode-bg": "#ecfdf5",
    "speculative.mode-border": "#a7f3d0",
    "pipeline.background": "#f8fafc",
    "pipeline.border": "#e2e8f0",
    "pipeline.active-background": "#eef2ff",
    "pipeline.active-border": "#c7d2fe",
    "pipeline.active-text": "#0f172a",
    "log.background": "#f1f5f9",
    "log.entry-background": "#ffffff",
    "log.msg": "#334155",
    "log.level-info": "#2563eb",
    "log.level-warn": "#d97706",
    "log.level-error": "#dc2626",
    "log.error-entry-bg": "#fef2f2",
    "header.status-bg": "#ffffff",
    "header.status-border": "#e2e8f0",
    "header.title-tracking": "-0.02em",
    "setting.row-divider": "#f1f5f9",
    "setting.nested-border": "#e2e8f0",
    "setting.code-bg": "#f1f5f9",
    "density.popup-width": "400px",
    "density.popup-height": "580px",
    "density.content-padding-x": "20px",
    "density.content-padding-y": "20px"
  }
})
